import type { Metadata } from "next";
import Link from "next/link";
import { Inter, Geist_Mono } from "next/font/google";
import DataStack from "../components/ui/dataStack"
import Moon from "../components/ui/Moon"
import Chevron from "@/components/ui/Chevron";

import "./globals.css";


const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Pump.Fun Graduates",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
     
     <body className={`${inter.variable} ${geistMono.variable} antialiased`}>
     <header className="header">
        <div className="title-content-container"> 
        <DataStack color={'#53A4FC'}/>
        <h1 className="title">PumpData</h1>
        <p className="title-subtext">Developer Docs</p>
        </div>
        <Moon color={"white"}/>
        </header>
        <main className="main-content-container">
        <nav className="sidebar">
        <Link href={'/'} className="sidebar-items">
          Welcome
          <Chevron color="white"/>
        </Link>
        <Link href={"/dashboard"} className="sidebar-items">
          Coin Dashboard
          <Chevron color="white"/>
        </Link>
        <div className="sidebar-items">
          Coin Data API
          <Chevron color="white"/>
        </div>  

        </nav>
        
        {children}
        
        </main>
      </body>
    </html>
  );
}
