import type { Metadata } from "next";
import { Inter, Geist_Mono } from "next/font/google";
import DataStack from "../components/ui/dataStack"
import Moon from "../components/ui/Moon"
import Chevron from "@/components/ui/Chevron";
import CollapsibleMenuItem from "@/components/ui/CollapsibleMenuItem";
import { motion } from "framer-motion"; 



import "@/styles/globals.css";




const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "pump.data",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const menuSections = [
    {
      title: "Welcome",
      subOptions: [
        { label: "What is pump.data?", href: "/" },
      ],
    },
    {
      title: "Meme Dashboard",
      subOptions: [
        { label: "Dashboard", href: "/dashboard" },
       
      ],
    },
    {
      title: "Data API",
      subOptions: [
        { label: "Getting Started", href: "/endpoint" },
        { label: "API Playground", href: "/endpoint" }
       
      ],
    }
  ];
  return (
    <html lang="en">
     
     <body className={`${inter.variable} ${geistMono.variable} antialiased`}>
     <script
          type="module"
          defer
          src="https://cdn.jsdelivr.net/npm/ldrs/dist/auto/grid.js"
        ></script>
     <header className="header">
        <div className="title-content-container"> 
        <DataStack color={'#53A4FC'}/>
        <h1 className="title">pump.data</h1>
        <p className="title-subtext">Developer Docs</p>
        </div>
        <Moon color={"white"}/>
        </header>
        <main className="main-content-container">
        <nav className="sidebar">
        
        <CollapsibleMenuItem sections={menuSections}/>

        </nav>
        
        {children}
        
        </main>
      </body>
    </html>
  );
}
